apiVersion: v1
data:
  AVP_AUTH_TYPE: apiKey
  AVP_CONJUR_ACCOUNT: default
  AVP_CONJUR_API_KEY: 31hh9fv2n0r8m11te296m1etqss34733ssfmkfvm12qqmrk3cwd778
  AVP_CONJUR_HOST: host/argocd-plugin
  AVP_CONJUR_SSL_CERT: |-
    -----BEGIN CERTIFICATE-----
    MIIDPTCCAiWgAwIBAgIUNB6vnBhxlKQIe7pzX7/wRY94uV0wDQYJKoZIhvcNAQEL
    BQAwQDEQMA4GA1UECgwHZGVmYXVsdDESMBAGA1UECwwJQ29uanVyIENBMRgwFgYD
    VQQDDA9jb25qdXIuaXRkLmRlbW8wHhcNMjMwMzAxMTAwMDE4WhcNMzMwMjI2MTAw
    MDE4WjAaMRgwFgYDVQQDDA9jb25qdXIuaXRkLmRlbW8wggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQC6n6WvGDHg0zv+TeVZS01cWg39/jVoFDh/yqoeZiLZ
    dxk4JeHM9SX3Q5fat94/Pq5rvG2kWEsJ3OLp+5tda7E7A0KNOIo5z7PlR2aF7NrL
    BjGtVqF+Lh+E7f5At+9zhkjT8qrZDx9kzXfL8hE0skd5LK2Wi339NGderA5PNzAK
    /a9nXBBh9cxLHCVZwi/D8FmLWyiWsppqOS6ZtlDBIYv0VKDRSC3306VJDbkeqvql
    Ax+AcqPcOT7/Xye2iXe7YSRGAco1ol54UTCcsoEXhAgL+ABqnaJoYg10GaLjIYxy
    JIW9YAk79Df71PEowTf2Y/pL3rUgt4TzIOjwjoXeCZVfAgMBAAGjVTBTMA4GA1Ud
    DwEB/wQEAwIFoDAdBgNVHQ4EFgQU2jmj7l5rSw0yVb/vlWAYkK/YBwkwIgYDVR0R
    BBswGYIPY29uanVyLml0ZC5kZW1vggZjb25qdXIwDQYJKoZIhvcNAQELBQADggEB
    ADvqxE89479du6kFqZ+yHUcHJxmwTWO+vCa8BnYMZDyqwCHtNaeDcCErM0SI3Asx
    dQgGo8BLw7sCVxoNof14XuHcSI6QYhDD0hd1BULah5teaWl5fBwWefDAD2mE3VF6
    Xo5kiXhGAQg08KDNZUMxKJ476U7CVG+B7DNRi9W0tkE3kewrYyR/v3rnHnmK/hIQ
    L/jjCnxUd1/vAA19SCrlOQ7G/xsu7ICBA4GlCEZLvuZ7b01SSGSwVS1VqfyAT3Jm
    Qc9zpEJxJTKPuXWtZXiI0/qWtgDOJaPkgM+AhAlK8EVlFJcl+mndwhfJk6FyXrgm
    FC6TnF4x9t2nC7WdbTjJ0xo=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDhTCCAm2gAwIBAgIJAJxOTTuBojcaMA0GCSqGSIb3DQEBCwUAMEAxEDAOBgNV
    BAoMB2RlZmF1bHQxEjAQBgNVBAsMCUNvbmp1ciBDQTEYMBYGA1UEAwwPY29uanVy
    Lml0ZC5kZW1vMB4XDTIzMDMwMTEwMDAwNVoXDTMzMDIyNjEwMDAwNVowQDEQMA4G
    A1UECgwHZGVmYXVsdDESMBAGA1UECwwJQ29uanVyIENBMRgwFgYDVQQDDA9jb25q
    dXIuaXRkLmRlbW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdCI97
    YS71Dfu7zM9b1RPGUoFDImz3kbtooes4ByQFX8uYVoMxJKXHNFLdiJ9Ia7GU0a5r
    LkU4TMTkHR8fjxouSIk8PzNG2HpQmeA8kQukBvRV2SYKnTXtVMx3WsKR9Ag24Bvm
    9suTlq10WzQro4NOtnxZRM1DBmGnOIaK+dZJB8oeoERBoN1V6H+upbUs+KBAJcnC
    jJerEzxajkA5dmQR0JPa+3NWjmzvtBAuUVxORsanx7g0TJAHbLdEbol77kAyejMd
    vBVtpbWaQd073Kj9Zjjpkne5Ivba/Mnfc2CvynZkaJSV/yznoyCL3uoihqTtwy91
    ac3qMWxXhIdqiJ9lAgMBAAGjgYEwfzAiBgNVHREEGzAZgg9jb25qdXIuaXRkLmRl
    bW+CBmNvbmp1cjAdBgNVHQ4EFgQU/TKfYx1bRyjVZap6Za0a3jMv9DwwHwYDVR0j
    BBgwFoAU/TKfYx1bRyjVZap6Za0a3jMv9DwwDAYDVR0TBAUwAwEB/zALBgNVHQ8E
    BAMCAeYwDQYJKoZIhvcNAQELBQADggEBAAMyNXYXaXgs9K6Xr7AHNLlB3wNFGLn3
    t3HGTxGq9y/+fKqJE4e0USnsjZ6K6MF7orYSMP4SnzNZdHuoGlMUbZx5oOuYla8r
    xA3Ib7bvtQH9GZhZwJI3RSZ+0zfzMa0kegYYjTUGpC/Bgf6FT27ZECskIHV6h3+V
    W2JNHsrhSF0ekuo8B5QjsTzyxRZX3TUsDawdGpVmQP+61i0St/+FCBQFo+umEYD3
    3fMTv6TnRLpe3G0KvPF09mPZTmx4RPOeD6j/ZwzReCCGCbeyg779ECx22ifoN1RI
    z+Ol5eVuyc6HWbTwW2Hdwy+4x76a1CyOd7jN/NHeE7juG2jXneZVWyU=
    -----END CERTIFICATE-----
  AVP_CONJUR_URL: https://conjur.itd.demo
  AVP_TYPE: conjurvault
kind: ConfigMap
metadata:
  name: vault-plugin-cm
  namespace: argocd
