apiVersion: v1
data:
  avp.yaml: |-
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "./"
      lockRepo: false
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd

